"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Check, CircleAlert, FileText, RefreshCw, X } from "lucide-react";
import type { CompanyFact, Page } from "@/db/schema";
import type { ExtractionPreview, ProfileSnapshot } from "@/lib/profile/service";
import { categories } from "@/lib/profile/facts";
import { api, dateLabel } from "@/lib/client";
import { Shell } from "./shell";
import { PageEvidence } from "./page-evidence";
import { AiSettingsPanel, type AiOverview } from "./ai-settings";

function FactCard({ fact, onSaved, onSource }: { fact: CompanyFact; onSaved: () => void; onSource: (id: string) => void }) {
  const [editing, setEditing] = useState(false), [draft, setDraft] = useState(fact), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [history, setHistory] = useState<{ id: string; snapshot: Record<string, unknown>; createdAt: string }[] | null>(null);
  async function review(status: CompanyFact["status"]) {
    setBusy(true); setError("");
    try { await api(`/api/facts/${fact.id}`, { method: "PATCH", body: JSON.stringify({ category: draft.category, subject: draft.subject, attribute: draft.attribute, value: draft.value, status, revision: fact.revision, reviewNote: draft.reviewNote }) }); onSaved(); setEditing(false); }
    catch (error) { setError(error instanceof Error ? error.message : "Could not save review."); } finally { setBusy(false); }
  }
  async function loadHistory() { try { setHistory(await api(`/api/facts/${fact.id}/history`)); } catch { setError("Could not load review history."); } }
  return <article className="panel fact-card" id={`fact-${fact.id}`}>
    <div className="fact-top"><span className={`badge ${fact.status === "confirmed" ? "success" : ""}`}>{fact.status === "confirmed" && <Check size={12} />}{fact.status}</span><span>{fact.category.replaceAll("_", " ")}</span><small>{fact.origin === "model" ? fact.confidence === null ? "Edited proposal · model score no longer applies" : `Model confidence: ${Math.round(fact.confidence * 100)}% · uncalibrated` : "Human-added"}</small></div>
    <h3>{fact.subject} · {fact.attribute}</h3><p className="fact-value">{fact.value}</p>
    <p className="helper-note">Revision {fact.revision} · {fact.reviewedAt ? `Reviewed ${dateLabel(fact.reviewedAt)}` : `Proposed ${dateLabel(fact.createdAt)}`}. Confirmation is your review decision; a website quote is not independent verification.</p>
    {fact.sources.map((source, index) => <div className="fact-source" key={index}><blockquote>{source.quote}</blockquote><a href={source.url} target="_blank" rel="noreferrer" className="mono">{source.url} ↗</a><p className="helper-note">Collected {dateLabel(source.fetchedAt)}</p><button className="button ghost small" onClick={() => onSource(source.pageId)}>Inspect saved page<ArrowRight size={12} /></button></div>)}
    {editing && <div className="profile-form-grid"><label>Category<select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Subject<input value={draft.subject} maxLength={180} onChange={(e) => setDraft({ ...draft, subject: e.target.value })} /></label><label>Specific attribute<input value={draft.attribute} maxLength={180} onChange={(e) => setDraft({ ...draft, attribute: e.target.value })} /></label><label className="full-width">Fact<textarea value={draft.value} maxLength={2000} onChange={(e) => setDraft({ ...draft, value: e.target.value })} /></label><label className="full-width">Review note<textarea value={draft.reviewNote} maxLength={1000} onChange={(e) => setDraft({ ...draft, reviewNote: e.target.value })} /></label></div>}
    {!editing && fact.reviewNote && <p>Review note: {fact.reviewNote}</p>}
    {error && <p className="notice" role="alert">{error}</p>}
    <div className="actions fact-actions"><button className="button primary small" disabled={busy || (!editing && fact.status === "confirmed")} onClick={() => review("confirmed")}>{editing ? "Save & confirm" : "Accept fact"}</button><button className="button ghost small" disabled={busy} onClick={() => { setEditing(!editing); setDraft(fact); }}>{editing ? "Cancel edit" : "Edit"}</button><button className="button ghost small" disabled={busy || fact.status === "rejected"} onClick={() => review("rejected")}>Reject</button>{fact.status !== "unreviewed" && <button className="button ghost small" disabled={busy} onClick={() => review("unreviewed")}>Return to review</button>}<button className="button ghost small" onClick={loadHistory}>Review history</button></div>
    {history && <details open className="fact-history"><summary>Previous revisions ({history.length})</summary>{history.length ? history.map((entry) => <div key={entry.id}><p>{dateLabel(entry.createdAt)} · {String(entry.snapshot.status)} · {String(entry.snapshot.subject)} / {String(entry.snapshot.attribute)}</p><p>{String(entry.snapshot.value)}</p><small>{String(entry.snapshot.reviewNote || "No review note")}</small></div>) : <p>No previous revisions.</p>}</details>}
  </article>;
}

function ExtractionPanel({ projectId, crawlId, remaining, revision, onQueued }: { projectId: string; crawlId: string; remaining: number; revision: string; onQueued: () => void }) {
  const [preview, setPreview] = useState<ExtractionPreview | null>(null), [selected, setSelected] = useState<string[]>([]), [force, setForce] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  useEffect(() => { const controller = new AbortController();
    api<ExtractionPreview>(`/api/projects/${projectId}/profile/preview?crawlId=${crawlId}`, { signal: controller.signal }).then((data) => { if (!controller.signal.aborted) { setPreview(data); setSelected(data.suggestedIds); setError(""); } }).catch((error) => { if (!controller.signal.aborted) setError(error.message); });
    return () => controller.abort();
  }, [projectId, crawlId, revision]);
  async function start() { setBusy(true); setError(""); setNotice("");
    try { const result = await api<{ reused: boolean }>(`/api/projects/${projectId}/profile/extract`, { method: "POST", body: JSON.stringify({ crawlId, pageIds: selected, force }) }); setNotice(result.reused ? "This extraction already completed. Its saved facts are shown below; no new model calls were made." : "Extraction queued. New facts will appear for review."); onQueued(); }
    catch (error) { setError(error instanceof Error ? error.message : "Could not start extraction."); } finally { setBusy(false); }
  }
  const chars = preview?.sources.filter((source) => selected.includes(source.id)).reduce((sum, source) => sum + source.characters, 0) || 0;
  return <section className="panel extraction-panel"><div className="section-heading"><div><h2>Extract from saved pages</h2><p>Review the source selection before sending text to a provider.</p></div></div>
    {error && <p className="notice" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}
    {preview ? <><p>{preview.note}</p><p className="helper-note">Crawl: {preview.crawlStatus}. Choose up to {preview.settings.pageLimit} pages. Approximately {Math.ceil(chars / 4).toLocaleString()} source tokens using a rough characters/4 estimate, excluding instructions; actual usage varies. Normally {selected.length} requests; at most {selected.length * (preview.settings.fallback ? 8 : 4)} with retries and one output repair per page. {remaining} project requests remain. Free-route token cost estimate: $0; NVIDIA account allowance and provider access are not guaranteed.</p>
      <div className="profile-sources">{preview.sources.map((source) => <label className="profile-source-choice" key={source.id}><input type="checkbox" checked={selected.includes(source.id)} disabled={!selected.includes(source.id) && selected.length >= preview.settings.pageLimit} onChange={(e) => setSelected(e.target.checked ? [...selected, source.id] : selected.filter((id) => id !== source.id))} /><span><strong>{source.title || "Untitled page"}</strong><small className="mono">{source.url}</small><small>{source.characters.toLocaleString()} characters{source.truncated ? " · excerpt truncated" : ""}</small></span></label>)}</div>
      {!preview.sources.length && <p>No readable text is available in this crawl.</p>}
      <label className="profile-checkbox"><input type="checkbox" checked={force} onChange={(e) => setForce(e.target.checked)} />Request a fresh extraction even if the same selection and settings were already processed</label>
      <button className="button primary" disabled={busy || !selected.length || remaining < selected.length} onClick={start}>{busy ? "Queuing…" : `Extract facts from ${selected.length} pages`}<ArrowRight size={14} /></button>
    </> : !error && <p>Loading saved sources…</p>}
  </section>;
}

function ManualFact({ projectId, crawlId, onSaved }: { projectId: string; crawlId: string; onSaved: () => void }) {
  const [sources, setSources] = useState<ExtractionPreview["sources"]>([]), [source, setSource] = useState<Page | null>(null);
  const [pageId, setPageId] = useState(""), [draft, setDraft] = useState({ category: "other_claim", subject: "", attribute: "", value: "", quote: "", reviewNote: "" }), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { const controller = new AbortController(); api<ExtractionPreview>(`/api/projects/${projectId}/profile/preview?crawlId=${crawlId}`, { signal: controller.signal }).then((data) => { if (!controller.signal.aborted) setSources(data.sources); }).catch((error) => { if (!controller.signal.aborted) setError(error.message); }); return () => controller.abort(); }, [projectId, crawlId]);
  async function choose(id: string) { setPageId(id); setSource(null); setDraft((d) => ({ ...d, quote: "" })); try { if (id) { const page = await api<Page>(`/api/pages/${id}`); setSource(page); } } catch { setError("Could not load source text."); } }
  async function save() { setBusy(true); setError(""); try { await api(`/api/projects/${projectId}/facts`, { method: "POST", body: JSON.stringify({ ...draft, pageId }) }); setDraft({ category: "other_claim", subject: "", attribute: "", value: "", quote: "", reviewNote: "" }); onSaved(); } catch (error) { setError(error instanceof Error ? error.message : "Could not add fact."); } finally { setBusy(false); } }
  return <details className="panel manual-fact"><summary>Add a human-confirmed fact</summary><p className="helper-note">Add your own fact with a quote from a saved page. No AI key or model request is needed.</p><div className="profile-form-grid"><label className="full-width">Source page<select value={pageId} onChange={(e) => void choose(e.target.value)}><option value="">Choose a saved page</option>{sources.map((p) => <option key={p.id} value={p.id}>{p.title || p.url}</option>)}</select></label><label>Category<select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label>{(["subject", "attribute", "value", "quote", "reviewNote"] as const).map((field) => <label className={field === "subject" || field === "attribute" ? "" : "full-width"} key={field}>{field === "quote" ? "Exact quote from the saved text (16–1,000 characters)" : field === "reviewNote" ? "Review note" : field}<textarea value={draft[field]} maxLength={field === "value" ? 2000 : field === "subject" || field === "attribute" ? 180 : 1000} onChange={(e) => setDraft({ ...draft, [field]: e.target.value })} /></label>)}</div>{source && source.id === pageId && <details><summary>Read saved source text</summary><div className="manual-source-text">{source.visibleText}</div></details>}{error && <p role="alert" className="notice">{error}</p>}<button className="button secondary small" disabled={busy || !pageId} onClick={save}>Add & confirm fact</button></details>;
}

export function CompanyProfile({ projectId }: { projectId: string }) {
  const [data, setData] = useState<ProfileSnapshot | null>(null), [ai, setAi] = useState<AiOverview | null>(null), [brandId, setBrandId] = useState(""), [crawlId, setCrawlId] = useState(""), [revision, setRevision] = useState(0), [error, setError] = useState("");
  const [status, setStatus] = useState("unreviewed"), [category, setCategory] = useState(""), [query, setQuery] = useState(""), [page, setPage] = useState(1), [selectedPage, setSelectedPage] = useState<string | null>(null);
  const refresh = () => setRevision((value) => value + 1);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    async function poll() { try {
      const [profile, overview] = await Promise.all([api<ProfileSnapshot>(`/api/projects/${projectId}/profile?brandId=${brandId}`, { signal: controller.signal }), api<AiOverview>(`/api/projects/${projectId}/ai`, { signal: controller.signal })]);
      if (controller.signal.aborted) return; setData(profile); setAi(overview); setError("");
      if (profile.jobs.some((job) => ["queued", "running"].includes(job.status))) timer = setTimeout(poll, 2500);
    } catch (error) { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : "Could not load company profile."); } }
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [projectId, brandId, revision]);
  async function cancel(id: string) { try { await api(`/api/profile-jobs/${id}/cancel`, { method: "POST", body: "{}" }); refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Could not cancel."); } }
  if (!data || !ai) return <Shell projectId={projectId}><main id="main" className="main"><h1>Company profile</h1>{error ? <p role="alert" className="notice">{error}<button className="button ghost small" onClick={refresh}>Retry</button></p> : <p>Loading profile and model availability…</p>}</main></Shell>;
  const selectedCrawl = data.runs.find((run) => run.id === crawlId && !["queued", "running"].includes(run.status))?.id || data.runs.find((run) => !["queued", "running"].includes(run.status) && run.pagesFetched > 0)?.id || "";
  const filtered = data.facts.filter((fact) => (!status || fact.status === status) && (!category || fact.category === category) && `${fact.subject} ${fact.attribute} ${fact.value}`.toLowerCase().includes(query.toLowerCase()));
  const maxPage = Math.max(1, Math.ceil(filtered.length / 12)), currentPage = Math.min(page, maxPage);
  return <Shell projectId={projectId} projectName={data.project.name}><main id="main" className="main company-profile">
    <div className="page-heading compact"><p className="eyebrow">Company source of truth</p><h1>Claims you can trace.<br />Facts you can review.</h1><p>Model proposals stay separate from the facts you confirm. This profile does not measure AI visibility.</p></div>
    {error && <p className="notice" role="alert">{error}<button className="button ghost small" onClick={refresh}>Retry</button></p>}
    <AiSettingsPanel projectId={projectId} initial={ai} onSaved={refresh} />
    <div className="profile-scope"><label>Website<select value={data.selectedBrandId} onChange={(e) => { setBrandId(e.target.value); setCrawlId(""); setData(null); setPage(1); }}>{data.sites.map((site) => <option key={site.id} value={site.id}>{site.name}{site.active ? "" : " (archived)"}</option>)}</select></label><label>Source crawl<select value={selectedCrawl} onChange={(e) => setCrawlId(e.target.value)}><option value="">Choose a completed or partial crawl</option>{data.runs.filter((run) => !["queued", "running"].includes(run.status)).map((run) => <option key={run.id} value={run.id}>{dateLabel(run.createdAt)} · {run.status} · {run.pagesFetched} pages</option>)}</select></label><button className="button ghost small" onClick={refresh}><RefreshCw size={14} />Refresh</button></div>
    {selectedCrawl ? <><ExtractionPanel key={selectedCrawl} projectId={projectId} crawlId={selectedCrawl} remaining={ai.remaining} revision={JSON.stringify(ai.settings)} onQueued={refresh} /><ManualFact key={`manual-${selectedCrawl}`} projectId={projectId} crawlId={selectedCrawl} onSaved={refresh} /></> : <div className="panel"><FileText size={24} /><h2>Collect website evidence first.</h2><p>Start a crawl in Website, then return here to build the company profile.</p></div>}
    {data.jobs.length > 0 && <details className="panel profile-job-history" open><summary>Extraction history</summary>{data.jobs.map((job) => <div className="profile-job" key={job.id}><div><strong>{job.status}</strong><p>{dateLabel(job.createdAt)} · {job.processed}/{job.pageIds.length} pages successfully processed · {job.factsCreated} new facts · {job.settings.primary} first</p><small>{job.settings.model} · {job.promptVersion}</small>{job.error && <p role="status">{job.error}</p>}{job.warnings.length > 0 && <details><summary>{job.warnings.length} page warnings</summary><ul>{job.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul></details>}</div>{["queued", "running"].includes(job.status) && <button className="button ghost small" disabled={job.cancelRequested} onClick={() => cancel(job.id)}><X size={12} />{job.cancelRequested ? "Cancelling…" : "Cancel"}</button>}</div>)}</details>}
    <div className="metrics-strip">{(["unreviewed", "confirmed", "rejected"] as const).map((value) => <div key={value}><span>{value}</span><strong>{data.facts.filter((f) => f.status === value).length}</strong><small>All saved facts for this website</small></div>)}<div><span>Potential contradictions</span><strong>{data.conflicts.length}</strong><small>Review matching attributes with different values</small></div></div>
    {data.conflicts.length > 0 && <details className="panel profile-conflicts" open><summary><CircleAlert size={16} />Potential contradictions ({data.conflicts.length})</summary><p className="helper-note">A deterministic comparison finds differing values for the same subject and attribute. It cannot find every semantic contradiction. Inspect dates and context, then edit attributes or reject an incorrect fact to resolve the group.</p>{data.conflicts.map((conflict, i) => <div className="profile-conflict" key={i}><strong>{conflict.subject} · {conflict.attribute}</strong><ul>{conflict.values.map((value) => <li key={value}>{value}</li>)}</ul><p>{conflict.explanation}</p><button className="button ghost small" onClick={() => { setStatus(""); setCategory(conflict.category); setQuery(conflict.attribute); setPage(1); }}>Review these facts</button></div>)}</details>}
    <section><div className="section-heading"><h2>Review company facts</h2><span className="count">{filtered.length}</span></div><div className="table-toolbar"><input aria-label="Search facts" placeholder="Search subject, attribute or fact…" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} /><select aria-label="Review status" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All review states</option><option value="unreviewed">Unreviewed</option><option value="confirmed">Confirmed</option><option value="rejected">Rejected</option></select><select aria-label="Fact category" value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }}><option value="">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></div>
      {filtered.slice((currentPage - 1) * 12, currentPage * 12).map((fact) => <FactCard key={`${fact.id}-${fact.revision}`} fact={fact} onSaved={refresh} onSource={setSelectedPage} />)}{!filtered.length && <p className="panel">No facts match this view. Extract facts from saved pages, add a sourced fact yourself, or change the filters.</p>}
      {filtered.length > 12 && <div className="table-footer"><span>Page {currentPage} / {maxPage}</span><div className="actions"><button className="button ghost small" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</button><button className="button ghost small" disabled={currentPage === maxPage} onClick={() => setPage(currentPage + 1)}>Next</button></div></div>}
    </section>
    <details className="panel profile-usage"><summary>AI usage & provider attempts</summary><p>{ai.total.attempts} requests used · {ai.remaining} remaining in the project’s total lifetime budget</p><p className="helper-note">Reported input tokens: {ai.total.inputTokens ?? "unknown"}; output tokens: {ai.total.outputTokens ?? "unknown"}. {ai.total.unknownUsage || 0} attempts have incomplete token usage. Reported cost subtotal: {ai.total.knownCost === null ? "unknown" : `$${ai.total.knownCost.toFixed(6)}`}; {ai.total.unknownCost || 0} attempts have unknown cost. Failed and cancelled attempts can still consume provider allowance. Latest 100 attempts shown.</p><div className="table-scroll"><table><thead><tr><th>When / purpose</th><th>Endpoint / model</th><th>Status</th><th>Tokens in / out</th></tr></thead><tbody>{ai.entries.map((entry) => <tr key={entry.id}><td>{dateLabel(entry.createdAt)}<small>{entry.purpose}</small></td><td>{entry.provider}<small className="mono">{entry.model}</small>{entry.servedModel && entry.servedModel !== entry.model && <small>Reported model: {entry.servedModel}</small>}{entry.upstream && <small>Upstream: {entry.upstream}</small>}</td><td>{entry.status}{entry.error && <small>{entry.error}</small>}</td><td>{entry.inputTokens ?? "?"} / {entry.outputTokens ?? "?"}</td></tr>)}</tbody></table></div></details>
  </main><PageEvidence key={selectedPage || "closed"} pageId={selectedPage} onClose={() => setSelectedPage(null)} /></Shell>;
}
