"use client";
import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, Download, RefreshCw } from "lucide-react";
import { Shell } from "./shell";
import { api, dateLabel } from "@/lib/client";
import type { InsightSnapshot } from "@/lib/insights/service";
import type { ExperimentAnswer } from "@/db/schema";
import type { ReferenceFact, Recommendation } from "@/lib/insights/types";
import { resultStatus } from "@/lib/presentation";
import { pretty, stages, stageLabels, questionTypes } from "@/lib/questions/types";

type Section = "visibility" | "competitors" | "citations" | "content" | "recommendations" | "reports";
const headings: Record<Section, [string, string]> = {
  visibility: ["What does AI say about you?", "See whether your brand comes up when buyers ask questions."],
  competitors: ["See the comparison.", "Compare mentions and content from the same research sample."],
  citations: ["Where answers point.", "Explore the links included in saved answers."],
  content: ["Make useful answers easier to find.", "See which buyer questions your pages answer, and where more detail may help."],
  recommendations: ["Your next steps, in order.", "Start with these improvements. Open any action to see why it matters and how to finish it."],
  reports: ["Share a clear picture.", "Export the findings, supporting evidence and a plan for the next 90 days."],
};
const percent = (value: number | null) => value === null ? "—" : Math.round(value * 100) + "%";
type Rate = { value: number | null; numerator: number; denominator: number; interval: number[] | null; confidence: string };
function Metric({ title, rate, explanation }: { title: string; rate: Rate; explanation: string }) {
  return <article className="insight-metric"><h3>{title}</h3><p className="insight-number">{percent(rate.value)}</p><p>{rate.numerator} of {rate.denominator} · {rate.confidence.startsWith("95%") ? "Sample result" : rate.confidence}</p><details className="simple-details"><summary>How this is calculated</summary><p>{explanation}</p>{rate.interval && <p>95% interval: {percent(rate.interval[0])}–{percent(rate.interval[1])}. {rate.confidence}</p>}</details></article>;
}
function EvidenceAnswer({ projectId, runId, id }: { projectId: string; runId: string; id: string }) {
  const [data, setData] = useState<{ answer: ExperimentAnswer; facts: ReferenceFact[] } | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function load() { if (data || loading) return; setLoading(true); try { setData(await api(`/api/projects/${projectId}/experiments/${runId}/answers/${id}`)); setError(""); } catch { setError("Could not load the saved answer."); } finally { setLoading(false); } }
  return <details className="simple-details answer-evidence" onToggle={(e) => { if (e.currentTarget.open) void load(); }}><summary>Read saved answer & evidence</summary>
    {error && <p role="alert">{error} <button className="button ghost small" onClick={load}>Retry</button></p>}
    {!data ? <p role="status">{loading ? "Opening answer…" : "No answer loaded."}</p> : <><h4>Exact question</h4><pre>{data.answer.payload.prompt}</pre><h4>Saved answer</h4><pre>{data.answer.payload.raw || "No answer text was saved."}</pre>
      <p className="helper-note">{dateLabel(data.answer.payload.observedAt)} · {data.answer.payload.truncated ? "Incomplete answer; excluded from metrics." : "Original saved text."}</p>
      {data.answer.payload.analysis?.refused && <p>The answer declined to respond: {data.answer.payload.analysis.refusalReason}</p>}
      {data.answer.payload.analysis?.brands.map((b) => <article key={b.brandId}><p><strong>{b.recommended ? "Recommended" : "Mentioned"}</strong> · {b.sentiment} · confidence {percent(b.confidence)}</p><blockquote>{b.quote}</blockquote><p>{b.rationale}</p>{b.reasons.map((s, i) => <p key={i}>{s}</p>)}{b.limitations.map((s, i) => <p key={i}>Limitation: {s}</p>)}</article>)}
      {data.answer.payload.analysis?.claims.map((c, i) => <article key={i}><blockquote>{c.quote}</blockquote><p>{pretty(c.classification)} · confidence {percent(c.confidence)}. {c.rationale}</p>{data.facts.filter((f) => c.factIds.includes(f.id)).map((f) => <div key={f.id}><p>Website claim: {f.value}</p>{f.sources.map((s, k) => <div key={k}><a href={s.url} target="_blank" rel="noreferrer">{s.url} ↗</a><blockquote>{s.quote}</blockquote><small>Collected {dateLabel(s.fetchedAt)}</small></div>)}</div>)}</article>)}
      <details className="simple-details"><summary>Method and collection details</summary><p>{data.answer.payload.provider} / {data.answer.payload.model}. {data.answer.payload.notes}</p><p>Each live answer uses a fresh conversation. Company source facts are used only for the separate analysis step. Imported answers have uncontrolled sampling conditions.</p></details>
    </>}
  </details>;
}
function ActionCard({ action }: { action: Recommendation }) {
  return <article className="insight-row"><h3>{action.title}</h3><p>{action.reason}</p><p className="helper-note">{action.effort} effort · Suggested for month {action.month}</p><details className="simple-details"><summary>How to do this & why it helps</summary><p>{action.expectedResult}</p><p>Suggested owner: {action.owner}</p><h4>What to do</h4><ul>{action.acceptance.map((a, i) => <li key={i}>{a}</li>)}</ul><h4>Supporting evidence</h4>{action.evidence.map((e, i) => <p key={i}>{e}</p>)}{action.urls.map((url) => <p key={url}><a href={url} target="_blank" rel="noreferrer">{url} ↗</a></p>)}<p>Priority {action.priority}/100 · confidence {percent(action.confidence)}. Inputs: commercial impact {action.inputs.commercialImpact}, visibility gap {action.inputs.visibilityGap}, confidence {action.inputs.confidence}, relevance {action.inputs.strategicRelevance}, ease {action.inputs.ease}.</p></details></article>;
}
function ImportAnswers({ projectId, done }: { projectId: string; done: () => void }) {
  const [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const data = new FormData(event.currentTarget), csv = data.get("csv") as File;
    try {
      if (csv?.size > 250000) throw new Error("Choose a CSV smaller than 250 KB.");
      const payload = csv?.size ? { csv: await csv.text() } : { answer: Object.fromEntries(["provider", "model", "question", "answer", "citation_urls", "observed_at", "notes"].map((k) => [k, String(data.get(k) || "")])) };
      await api(`/api/projects/${projectId}/imports`, { method: "POST", body: JSON.stringify(payload) }); done();
    } catch (e) { setError(e instanceof Error ? e.message : "Import failed."); } finally { setBusy(false); }
  }
  return <details className="simple-details panel"><summary>Add answers collected elsewhere</summary><p>Optional. Paste one answer or choose a CSV. Original text is saved; AI analysis uses your existing allowance. Imported samples stay separate from live checks.</p>
    <form onSubmit={submit} className="insight-form"><fieldset disabled={busy}><label>CSV file<input type="file" name="csv" accept=".csv,text/csv" /></label><p className="helper-note">Columns: provider, model, question, answer, citation_urls, observed_at, notes. Quote cells containing commas or line breaks. Separate citation URLs with semicolons. Up to 100 rows.</p>
      <div className="insight-fields"><label>Answer source<input name="provider" maxLength={120} placeholder="Tool used to collect the answer" /></label><label>Model, if known<input name="model" maxLength={160} placeholder="Unknown" /></label><label>Observation date<input name="observed_at" type="date" /></label></div>
      <label>Buyer question<textarea name="question" maxLength={4000} rows={2} /></label><label>Complete answer<textarea name="answer" maxLength={24000} rows={6} /></label><label>Citation URLs<textarea name="citation_urls" maxLength={4000} rows={2} /></label><label>Notes<textarea name="notes" maxLength={1000} rows={2} /></label>
      {error && <p className="notice" role="alert">{error}</p>}<button className="button secondary" type="submit">{busy ? "Saving…" : "Save and analyze answers"}</button>
    </fieldset></form></details>;
}
export function InsightsWorkspace({ projectId, section }: { projectId: string; section: Section }) {
  const [data, setData] = useState<InsightSnapshot | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  const [filters, setFilters] = useState({ run: "", stage: "", type: "", persona: "", from: "", to: "", provider: "", question: "" }), [samples, setSamples] = useState(1), [answerPage, setAnswerPage] = useState(1), [showAllGaps, setShowAllGaps] = useState(false);
  const [estimate, setEstimate] = useState<{ answers: number; expectedRequests: number; remaining: number; explanation: string } | null>(null), [tour, setTour] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    async function poll() {
      try { const next = await api<InsightSnapshot>(`/api/projects/${projectId}/insights?${new URLSearchParams(filters)}`, { signal: controller.signal }); if (controller.signal.aborted) return; setData(next); }
      catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : "Could not load results."); }
      if (!controller.signal.aborted) timer = setTimeout(poll, 8000);
    }
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [projectId, filters, revision]);
  async function act(path: string, body: object = {}) {
    setBusy(true); setError("");
    try { const result = await api<{ id?: string }>(`/api/projects/${projectId}/${path}`, { method: "POST", body: JSON.stringify(body) }); if (path === "experiments" && result.id) setFilters((f) => ({ ...f, run: result.id! })); setRevision((v) => v + 1); setEstimate(null); }
    catch (e) { setError(e instanceof Error ? e.message : "Could not start the work."); } finally { setBusy(false); }
  }
  function filter(key: keyof typeof filters, value: string) { setFilters((old) => ({ ...old, [key]: value, ...(key === "run" ? { provider: "" } : {}) })); setAnswerPage(1); }
  const [title, description] = headings[section];
  if (!data) return <Shell projectId={projectId}><main id="main" className="main"><h1>{title}</h1><p role={error ? "alert" : "status"}>{error || "Opening your saved research…"}</p><button className="button secondary" onClick={() => setRevision((v) => v + 1)}>Refresh</button></main></Shell>;
  const m = data.metrics, running = data.run && ["running", "queued"].includes(data.run.status), contentRunning = data.content && ["running", "queued"].includes(data.content.status);
  const blankRate: Rate = { value: null, numerator: 0, denominator: 0, interval: null, confidence: "No eligible evidence" };
  const result = data.content?.result, base = `/api/projects/${projectId}/export/`;
  const activeFilters = Object.entries(filters).filter(([key, value]) => key !== "run" && !!value).length;
  const pageSize = 5, pageCount = Math.max(1, Math.ceil(data.answers.length / pageSize)), currentPage = Math.min(answerPage, pageCount);
  const tourSteps = [
    ["Start with the result", "AI results tell you how often the brand appears in saved answers. Every percentage includes a sample count."],
    ["Open the evidence", "Read an answer below to see the exact question, response and comparison with website claims."],
    ["Find useful changes", "Content ideas and your Action plan turn page evidence into a 30-day and 90-day plan."],
    ["Share what you learned", "Report includes print-to-PDF and exports. All demonstration results are fictional."],
  ];
  return <Shell projectId={projectId} projectName={data.project.name}><main id="main" className="main insights-workspace">
    <div className="page-heading compact"><p className="eyebrow">{{ visibility: "AI results", competitors: "Competitors", citations: "Sources in answers", content: "Content ideas", recommendations: "Action plan", reports: "Report" }[section]}</p><h1>{title}</h1><p>{description}</p></div>
    {error && <p className="notice" role="alert">{error}<button className="button ghost small" onClick={() => { setError(""); setRevision((v) => v + 1); }}>Try again</button></p>}
    {data.demo && <details className="simple-details demo-tour"><summary>How to read this sample project</summary><h2>{tourSteps[tour][0]}</h2><p>{tourSteps[tour][1]}</p><button className="button secondary small" onClick={() => setTour((v) => (v + 1) % tourSteps.length)}>{tour + 1} / {tourSteps.length} · Next<ArrowRight size={14} /></button></details>}
    {["visibility", "competitors", "citations"].includes(section) && <>
      {running && <p role="status" className="notice">Checking buyer questions: {data.progress.completed} of {data.progress.total} analyzed. {data.progress.answered} answers saved. You can leave this page while the app stays running.</p>}
      {data.run?.mode === "manual" && <p className="notice">Imported answers · Dates, prompts and collection conditions were supplied manually. These are not controlled repeat samples.</p>}
      <details className="simple-details"><summary>Filters, previous checks & refresh options</summary>
      <div className="insight-toolbar"><label>Saved check<select value={filters.run || data.run?.id || ""} onChange={(e) => filter("run", e.target.value)}>{!data.runs.length && <option value="">No checks yet</option>}{data.runs.map((r) => <option key={r.id} value={r.id}>{dateLabel(r.createdAt)} · {r.mode === "manual" ? "Imported" : r.mode === "demo" ? "Demo" : "Live check"} · {resultStatus(r.status)}</option>)}</select></label>
        {!data.demo && (running ? <button className="button secondary" disabled={busy} onClick={() => act(`experiments/${data.run!.id}/stop`)}>Stop check</button> : <button className="button primary" disabled={busy} onClick={() => { setFilters((f) => ({ ...f, run: "" })); void act("experiments", { samples }); }}>{busy ? "Starting…" : "Check AI answers"}<ArrowRight size={15} /></button>)}
        {!data.demo && data.run?.mode === "api" && ["partial", "cancelled"].includes(data.run.status) && <button className="button secondary" disabled={busy} onClick={() => act(`experiments/${data.run!.id}/resume`)}>Continue unfinished answers</button>}
      </div>
<div className="insight-fields">
        <label>Buyer stage<select value={filters.stage} onChange={(e) => filter("stage", e.target.value)}><option value="">All stages</option>{stages.map((s) => <option key={s} value={s}>{stageLabels[s]}</option>)}</select></label>
        <label>Question type<select value={filters.type} onChange={(e) => filter("type", e.target.value)}><option value="">All types</option>{questionTypes.map((s) => <option key={s} value={s}>{pretty(s)}</option>)}</select></label>
        <label>Buyer type<select value={filters.persona} onChange={(e) => filter("persona", e.target.value)}><option value="">All buyer types</option>{data.personas.map((p) => <option key={p.id} value={p.id}>{p.role}</option>)}</select></label>
        <label>From<input type="date" value={filters.from} onChange={(e) => filter("from", e.target.value)} /></label><label>To<input type="date" value={filters.to} onChange={(e) => filter("to", e.target.value)} /></label>
        <label>Question contains<input value={filters.question} maxLength={200} onChange={(e) => filter("question", e.target.value)} /></label>
        <label>Answer source<select value={filters.provider} onChange={(e) => filter("provider", e.target.value)}><option value="">All sources in this check</option>{data.scopes.map((s) => <option key={s}>{s}</option>)}</select></label>
        <label>Answers per question<select value={samples} onChange={(e) => { setSamples(Number(e.target.value)); setEstimate(null); }}>{[1, 3, 5].map((s) => <option key={s} value={s}>{s}</option>)}</select></label></div>
        <button className="button ghost small" onClick={() => { setFilters({ run: "", stage: "", type: "", persona: "", from: "", to: "", provider: "", question: "" }); setAnswerPage(1); }}>Clear filters</button>
        {!data.demo && <button className="button secondary small" onClick={async () => { try { setEstimate(await api(`/api/projects/${projectId}/experiments/estimate?samples=${samples}`)); } catch (e) { setError(e instanceof Error ? e.message : "Estimate unavailable."); } }}>See planned usage</button>}
        {estimate && <p>{estimate.answers} planned answers · about {estimate.expectedRequests} requests · {estimate.remaining} requests remaining. {estimate.explanation}</p>}
      </details>
      {activeFilters > 0 && <p className="notice">{activeFilters} {activeFilters === 1 ? "filter is" : "filters are"} active. <button className="text-link" onClick={() => { setFilters((f) => ({ ...f, stage: "", type: "", persona: "", from: "", to: "", provider: "", question: "" })); setAnswerPage(1); }}>Show all results in this check</button></p>}
      <p className="helper-note">{m.eligible} analyzed answers{data.run ? " · " + dateLabel(data.run.createdAt) : ""}. Results describe this sample only.{m.scopes.length > 1 ? " This sample combines different AI sources; use the filters to separate them." : ""}</p>
      {!data.demo && data.run?.mode === "api" && ["partial", "cancelled"].includes(data.run.status) && <p className="notice">This check is unfinished. Saved answers are available below. <button className="text-link" disabled={busy} onClick={() => act(`experiments/${data.run!.id}/resume`)}>Continue check</button></p>}
    </>}
    {section === "visibility" && <>
      {m.eligible > 0 ? <section className="panel calm-answer-summary"><p className="eyebrow">From the saved answers</p><h2>Your brand appeared in <strong>{m.target?.mention.numerator ?? 0} of {m.eligible}</strong> answers.</h2><p>{m.target?.recommendation.numerator ?? 0} of those {m.eligible} answers recommended your brand as an option for buyers.</p><Link className="button primary" href={`/projects/${projectId}/recommendations`}>See what to improve<ArrowRight size={15} /></Link><p className="helper-note">Read the original answers below to see the context.</p></section> : <section className="panel"><h2>{running ? "Your answers are on the way." : "No analyzed answers in this view yet."}</h2><p>{running ? "Results appear here as each answer is saved and analyzed." : activeFilters ? "Try clearing your filters to see more saved answers." : "Start or continue your analysis from Home. We will prepare buyer questions and check what AI says."}</p>{!running && !activeFilters && <Link className="button primary" href={`/projects/${projectId}`}>Go to Home<ArrowRight size={15} /></Link>}</section>}
      <details className="simple-details"><summary>More result details</summary><div className="insight-metrics"><Metric title="Your brand was mentioned" rate={m.target?.mention || blankRate} explanation="Answers mentioning your brand divided by eligible analyzed answers, including refusals." /><Metric title="Your brand was recommended" rate={m.target?.recommendation || blankRate} explanation="Answers explicitly suggesting your brand as a buyer choice divided by eligible answers." /><Metric title="Answers linked to your website" rate={m.target?.citations || blankRate} explanation="Answers linking your domain divided by answers with any citation URL. A URL mention is not verified browsing." /><Metric title="Claims match saved website facts" rate={m.accuracy} explanation="Supported claims divided by supported plus contradicted claims. Unverifiable and time-sensitive claims are excluded. Website claims are not independently verified truth." /></div><p>{m.excluded} answers could not be counted. {m.refusals} declined to answer and remain included in the sample.</p></details>
      <details className="simple-details"><summary>Stages, history & measurement details</summary>
        {m.stages.map((s) => <p key={s.stage}>{pretty(s.stage)}: {percent(s.mention.value)} ({s.mention.numerator}/{s.mention.denominator})</p>)}
        <div className="insight-table"><table><thead><tr><th>Date</th><th>Kind</th><th>Brand mentions</th><th>Answers</th></tr></thead><tbody>{data.history.map((h) => <tr key={h.id}><td><button className="text-link" onClick={() => filter("run", h.id)}>{dateLabel(h.createdAt)}</button></td><td>{h.mode}</td><td>{percent(h.metrics.target?.mention.value ?? null)}</td><td>{h.metrics.eligible}</td></tr>)}</tbody></table></div>
        {data.comparison && <p>Previous comparable setup: {percent(data.comparison.metrics.target?.mention.value ?? null)} mentioned across {data.comparison.metrics.eligible} answers. {data.comparison.note}</p>}
        <p>{m.warning}</p>{m.scopeGroups.map((s) => <p key={s.scope}>{s.scope}: {s.mention.numerator}/{s.count} target mentions.</p>)}<p>{m.unverifiedClaims} unverifiable claims and {m.timeSensitiveClaims} time-sensitive claims are excluded from agreement rates.</p>
      </details>
    </>}
    {section === "competitors" && <><div className="insight-table"><table><thead><tr><th>Brand</th><th>Mentions</th><th>Recommendations</th><th>Weighted share</th><th>Average list position</th></tr></thead><tbody>{m.brands.map((b) => <tr key={b.id}><td>{b.name}{b.kind === "target" ? " · you" : ""}</td><td>{b.mention.numerator}/{b.mention.denominator}</td><td>{b.recommendation.numerator}/{b.recommendation.denominator}</td><td>{percent(b.share)} ({b.weighted}/{b.shareDenominator})</td><td>{b.position?.toFixed(1) || "—"} · {b.positionSamples} lists; absent in {b.absent} answers</td></tr>)}</tbody></table></div><details className="simple-details"><summary>How the comparison works</summary><p>Weighted share counts each tracked brand once per answer, weighted by buyer stage. Weights: discovery and education 1, research and risk review 2, comparison and purchase 3. Recommendation position uses explicit lists only. Missing brands are reported as absent, never as last place.</p></details><Link className="button secondary small" href={`/projects/${projectId}/content`}>Compare content coverage<ArrowRight size={14} /></Link><Link className="button ghost small" href={`/projects/${projectId}/settings`}>Manage competitor websites</Link></>}
    {section === "citations" && <><p>Top five domains account for {percent(m.concentration.value)} of captured URL occurrences ({m.concentration.numerator}/{m.concentration.denominator}).</p>{!m.citationDomains.length && <p className="panel">No citation URLs are available in the eligible answers. This model may not supply citations.</p>}{m.citationDomains.map((d) => <article className="insight-row" key={d.domain}><h2>{d.domain}{d.target ? " · your website" : ""}</h2><p>{d.count} URL occurrences in {d.answerIds.length} answers.</p><details className="simple-details"><summary>See captured links</summary>{d.urls.map((url) => <p key={url}><a href={url} target="_blank" rel="noreferrer">{url} ↗</a></p>)}<p>Captured from: {d.sourceKinds.map(pretty).join(", ")}. These URLs have not been opened or verified by AnswerLens.</p></details></article>)}</>}
    {["content", "recommendations", "reports"].includes(section) && <>
      {!data.demo && <details className="simple-details"><summary>Refresh or continue your plan</summary><div className="insight-toolbar"><button className="button secondary" disabled={busy} onClick={() => contentRunning ? act(`content/${data.content!.id}/stop`) : act("content")}>{contentRunning ? "Stop content analysis" : "Refresh content & plan"}<RefreshCw size={14} /></button>{data.content && ["partial", "cancelled"].includes(data.content.status) && <button className="button ghost small" disabled={busy} onClick={() => act(`content/${data.content!.id}/resume`)}>Continue unfinished pages</button>}</div></details>}
      {contentRunning && <p role="status">Reading content: {result?.pages.length || 0} of {data.content?.total} pages saved.</p>}
      {data.content?.status === "partial" && <p className="notice">Some content analysis is incomplete. Available rule checks and saved insights remain visible.</p>}
      {!result && <p className="panel">Your plan will appear when the analysis finishes reading your pages. Visit Home to start or continue the analysis.</p>}
    </>}
    {section === "content" && result && <>
      <section><h2>Questions that need a clearer answer</h2>{!result.gaps.length && <p>No gaps were recorded in the analyzed excerpts. Incomplete coverage may hide gaps.</p>}{result.gaps.slice(0, showAllGaps ? undefined : 3).map((g) => <article className="insight-row" key={g.id}><h3>{g.question}</h3><p>{g.reason}</p><details className="simple-details"><summary>Compare the page evidence</summary><p>{g.targetUrls.length ? "Matching target pages" : "Target pages inspected (no match found)"}</p>{(g.targetUrls.length ? g.targetUrls : g.checkedTargetUrls).map((u) => <p key={u}><a href={u} target="_blank" rel="noreferrer">{u} ↗</a></p>)}<p>Competitor matches</p>{g.competitorUrls.map((u) => <p key={u}><a href={u} target="_blank" rel="noreferrer">{u} ↗</a></p>)}{result.pages.flatMap((p) => p.matches.filter((match) => match.questionId === g.questionId).map((match, i) => <blockquote key={p.pageId + i}>{match.quote}<small>{p.url} · {match.reason}</small></blockquote>))}<p>Suggested action: {g.action}. Confidence {percent(g.confidence)}. Check whole-site coverage before deciding a new page is needed.</p></details></article>)}{result.gaps.length > 3 && <button className="button secondary small" aria-expanded={showAllGaps} onClick={() => setShowAllGaps((v) => !v)}>{showAllGaps ? "Show fewer ideas" : `Show all ${result.gaps.length} ideas`}</button>}</section>
      <details className="simple-details panel"><summary>Readiness scores, page inventory & coverage matrix</summary>
        <p>Internal diagnostic, not a ranking factor. Scores show earned points out of evaluated weight; unknown components are left out.</p>
        {data.content!.brands.map((b) => { const ps = result.pages.filter((p) => p.brandId === b.id); const score = ps.length ? Math.round(ps.reduce((s, p) => s + (p.score || 0), 0) / ps.length) : null; const weight = ps.length ? Math.round(ps.reduce((s, p) => s + p.evaluatedWeight, 0) / ps.length) : 0; return <p key={b.id}>{b.name}: average {score ?? "—"}/{weight} evaluated points across {ps.length} pages.</p>; })}
        <div className="insight-table"><table><thead><tr><th>Buyer question</th>{data.content!.brands.map((b) => <th key={b.id}>{b.name}</th>)}</tr></thead><tbody>{data.content!.questions.map((q) => [q.id, q.text] as const).map(([id, text]) => <tr key={id}><td>{text}</td>{data.content!.brands.map((b) => <td key={b.id}>{result.pages.filter((p) => p.brandId === b.id && p.matches.some((m) => m.questionId === id)).length} matched pages</td>)}</tr>)}</tbody></table></div>
        {result.pages.map((p) => <article className="insight-row" key={p.pageId}><h3>{p.title}</h3><a href={p.url} target="_blank" rel="noreferrer">{p.url} ↗</a><p>{p.pageType} · {p.topic} · {p.score ?? "—"}/{p.evaluatedWeight} evaluated points · {p.status}</p><details className="simple-details"><summary>Show score calculation and passages</summary>{p.components.map((c) => <div key={c.name}><h4>{c.name}: {c.points ?? "Unknown"} / {c.weight}</h4><p>{c.method === "rule" ? "Website check" : "AI judgment"} · {c.reason}</p>{c.quote && <blockquote>{c.quote}</blockquote>}{c.confidence !== null && <small>Confidence {percent(c.confidence)}</small>}</div>)}{p.matches.map((match) => <blockquote key={match.questionId}>{match.quote}<small>{match.reason}</small></blockquote>)}<p>Products: {p.products.join(", ") || "None identified"}. Buyer stages: {p.stages.map(pretty).join(", ") || "Unknown"}. Collected {dateLabel(p.fetchedAt)}. Read {p.excerptLength} characters.</p>{p.similarUrls.length > 0 && <p>Identical saved text: {p.similarUrls.join(", ")}</p>}</details></article>)}
        {result.coverage.map((c, i) => <p key={i}>{c}</p>)}
      </details>
    </>}
    {section === "recommendations" && result && <><section><h2>{result.recommendations.length ? "Start with these" : "No suggested actions yet"}</h2>{!result.recommendations.length && <p>No actions were saved from the available evidence. Check Home for unfinished analysis.</p>}{result.recommendations.length > 3 && <p className="helper-note">Your first 3 of {result.recommendations.length} suggested improvements. The full plan is below.</p>}{result.recommendations.slice(0, 3).map((r) => <ActionCard key={r.id} action={r} />)}</section><details className="simple-details panel"><summary>Your full 30-day and 90-day plan</summary>{[1, 2, 3].map((month) => <section key={month}><h2>{month === 1 ? "First 30 days · fix and clarify" : month === 2 ? "Days 31–60 · improve commercial pages" : "Days 61–90 · expand and measure again"}</h2>{result.recommendations.filter((r) => r.month === month).map((r) => <ActionCard key={r.id} action={r} />)}</section>)}<p>Suggested repeat check: {result.repeatOn}. The plan measures clearer information and changed answers; it does not promise rankings or citations.</p></details></>}
    {section === "reports" && <section className="panel"><h2>Your research, ready to share.</h2><p>The report includes the latest saved check, content findings, sources, limitations and action plan.</p><a href={base + "report"} target="_blank" rel="noreferrer" className="button primary">Open printable report<ArrowRight size={15} /></a><p className="helper-note">Use your browser’s Print command to save as PDF.</p><details className="simple-details"><summary>Download individual datasets</summary><div className="insight-downloads">{["questions", "results", "facts", "issues", "recommendations", "json"].map((kind) => <a className="button secondary small" key={kind} href={base + kind}><Download size={14} />{kind === "json" ? "Complete JSON backup" : pretty(kind) + " CSV"}</a>)}</div><p>Backup contains research evidence and source snapshots. Keys and owner configuration are excluded. No automatic restore is provided.</p></details></section>}
    {["visibility", "competitors", "citations"].includes(section) && <section className="insight-answers"><h2>Answers behind the numbers</h2>{data.answers.slice((currentPage - 1) * pageSize, currentPage * pageSize).map((a) => <article className="insight-row" key={a.id}><h3>{a.question.text}</h3><p className="helper-note">Answer {a.sample} · {resultStatus(a.status)} · {dateLabel(a.observedAt)}{a.truncated ? " · cut short" : ""}</p>{a.status === "completed" && a.analysis && !a.truncated && <p className="answer-outcome">{a.analysis.refused ? "AI declined to answer this question." : a.analysis.brands.some((b) => b.brandId === m.target?.id && b.recommended) ? "Your brand was recommended." : a.analysis.brands.some((b) => b.brandId === m.target?.id) ? "Your brand was mentioned." : "Your brand was not mentioned."}</p>}{a.error && <details className="simple-details"><summary>Why this answer is unfinished</summary><p>{a.error}</p></details>}{data.run && <EvidenceAnswer projectId={projectId} runId={data.run.id} id={a.id} />}</article>)}{!data.answers.length && <p>No saved answers match this view.</p>}<div className="insight-toolbar" aria-label="Answer pages"><button className="button ghost small" disabled={currentPage === 1} onClick={() => setAnswerPage(currentPage - 1)}>Previous</button><span>Page {currentPage} of {pageCount}</span><button className="button ghost small" disabled={currentPage >= pageCount} onClick={() => setAnswerPage(currentPage + 1)}>Next</button></div></section>}
    {section === "visibility" && !data.demo && <ImportAnswers projectId={projectId} done={() => { setFilters((f) => ({ ...f, run: "" })); setRevision((v) => v + 1); }} />}
    <div className="insight-toolbar"><Link className="text-link" href={`/projects/${projectId}`}>Back to Home</Link><Link className="text-link" href={`/projects/${projectId}/evidence`}>Website evidence ↗</Link></div>
  </main></Shell>;
}
